### ISSUE TITLE
Add an option to always include a mirror when serving the mirrorlist file

### ISSUE THREAD

**Issue by nvgoldin** [nvgoldin/mirrorchecker#4]
So the origin will always be included(or other sites for that matter).
This can be added as another option in the yaml file:
```yaml
- mirror:
     ...
     filter: False
```
